language: node_js
node_js:
  - "iojs"
  - node
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - npm install
install:
  - npm install -g firebase-tools
after_success:
  - firebase depoly --token $FIREBASE_TOKEN